fix: run kustomize build prior kube-linter

diff --git a/.github/workflows/kube-linter.yaml b/.github/workflows/kube-linter.yaml
--- a/.github/workflows/kube-linter.yaml
+++ b/.github/workflows/kube-linter.yaml
@@ -15,17 +15,23 @@ jobs:
       # This prepares directory where github/codeql-action/upload-sarif@v1 looks up report files by default.
       - name: Create ../results directory for SARIF report files
         shell: bash
-        run: mkdir -p ../results
+        run: mkdir -p ../results kustomizedfiles
+
+      - name: Setup Kustomize
+        uses: multani/action-setup-kustomize@v1
+        with:
+          version: 5.1.1
+
+      - name: Run kustomize build
+        run: |
+          for p in $(find argo-cd-apps components -name "*kustomization.yaml*"); do kustomize build ${p%/*} -o kustomizedfiles/${p//\//-} || echo "^ ERROR when running kustomize build for ${p%/*} ^"; done
 
       - name: Scan yaml files with kube-linter
         uses: stackrox/kube-linter-action@v1.0.4
         id: kube-linter-action-scan
         with:
-          # Adjust this to the location of kube-linter config you're using, or remove the setting if you'd like to use
-          # the default config.
-          config: ./.kubelinter.yaml
           # Adjust this directory to the location where your kubernetes resources and helm charts are located.
-          directory: .
+          directory: kustomizedfiles
           # The following two settings make kube-linter produce scan analysis in SARIF format which would then be
           # made available in GitHub UI via upload-sarif action below.
           format: sarif
