ci: use merge base when calculating diffs (#10730)
If the target branch of a PR has had activity, and the source branch
cannot be merged with a fast-forward strategy, render-diff will include
changes that have already landed in the target branch when calculating
the diff that a PR is introducing.  Instead, render-diff should be
calculating the merge-base between the source and the target branch as
the source to diff against.

Render-diff already supports this behavior so long as the `--base-ref`
option is not set.  Since we're setting it in our CI configuration,
unset it to obtain correct behavior.

v2:
- use the diff between the target branch and github's attempted merge
- warn when the attempted merge doesn't succeed

v3:
- fix step name for checking out the merge base

Signed-off-by: Andy Sadler <ansadler@redhat.com>

diff --git a/.github/workflows/pr-render-diff.yaml b/.github/workflows/pr-render-diff.yaml
--- a/.github/workflows/pr-render-diff.yaml
+++ b/.github/workflows/pr-render-diff.yaml
@@ -28,11 +28,20 @@ jobs:
         working-directory: infra-tools
         run: go build -o bin/render-diff ./cmd/render-diff
 
-      # Fetch the PR head ref and switch to it for analysis.
-      - name: Checkout PR head
+      # Fetch the PR merge ref and switch to it for analysis.
+      - name: Checkout PR merge ref
+        continue-on-error: true
+        id: fetch-merge
         run: |
-          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-head
-          git checkout pr-head
+          git fetch origin pull/${{ github.event.pull_request.number }}/merge:pr-merge
+          git checkout pr-merge
+
+      # if refs/pull/N/merge doesn't exist, warn about it in our logs and continue to fail
+      - name: Warn about required PR rebase
+        if: ${{ always() && steps.fetch-merge.outcome == 'failure' }}
+        run: |
+          echo "ERROR: This PR has merge conflicts and needs to be rebased before render-diff can run."
+          exit 1
 
       - name: Create output directory
         run: mkdir -p render-diff-output
@@ -53,7 +62,7 @@ jobs:
             --log-file=../render-diff-debug.log
 
       - name: Upload diff artifacts
-        if: always()
+        if: ${{ always() && steps.fetch-merge.outcome == 'success' }}
         uses: actions/upload-artifact@v4
         with:
           name: render-diff-output
